# Generated by Django 4.2.5 on 2023-10-29 15:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='Desconocido', max_length=20)),
                ('patente', models.CharField(default='Desconocido', max_length=20)),
                ('tipo_vehiculo', models.CharField(default='Desconocido', max_length=50)),
                ('marca', models.CharField(default='Desconocido', max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900)])),
                ('nro_motor', models.CharField(default='Sin especificar', max_length=100)),
                ('nro_chasis', models.CharField(default='Sin especificar', max_length=150)),
                ('imagen', models.ImageField(null=True, upload_to='imgprod')),
            ],
        ),
        migrations.CreateModel(
            name='Compañia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compañia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mant', models.DateField(default=django.utils.timezone.now)),
                ('kilometraje', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, default='', null=True)),
                ('tipo_mantencion', models.CharField(choices=[('Preventiva', 'Preventiva'), ('Correctiva', 'Correctiva'), ('Externa', 'Externa')], default='Preventiva', max_length=50)),
                ('sueldo_a_m', models.IntegerField(blank=True, default=0, null=True)),
                ('id_autobombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bomberos.autobombero')),
                ('id_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bomberos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_detalle', models.DateField(default=django.utils.timezone.now)),
                ('nombres_insumos', models.CharField(default='Sin insumos', max_length=100)),
                ('valor_insumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantidad_total_insumo', models.IntegerField(default=0)),
                ('valor_total_gastado', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=15, null=True)),
                ('horas_hombres_invertidas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mantencionpreventiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bomberos.mantencion')),
            ],
        ),
        migrations.AddField(
            model_name='autobombero',
            name='compañia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bomberos.compañia'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('capitan', 'Capitán'), ('mecanico', 'Mecánico'), ('comandante', 'Comandante')], default='mecanico', max_length=10)),
                ('compañia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bomberos.compañia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
