# Generated by Django 4.2.5 on 2023-12-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_insumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad_insumo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DetMant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_aplic', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('h_h_aplic', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.IntegerField(primary_key=True, serialize=False)),
                ('nomb_insumo', models.CharField(default='Sin nombre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionDiaria',
            fields=[
                ('id_rev_dia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_salida', models.CharField(max_length=10)),
                ('hora_llegada', models.CharField(max_length=10)),
                ('km_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hora_motor', models.IntegerField()),
                ('hora_bomba', models.IntegerField()),
                ('est_carro', models.CharField(max_length=30)),
                ('observaciones', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_servicio', models.CharField(default='', max_length=20)),
                ('descripcion', models.TextField(default='')),
                ('costo_serv', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='TareaInterna',
            fields=[
                ('id_tarea', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Sin descripción', max_length=50)),
                ('tipo_tarea', models.CharField(default='Sin tipo', max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='autobombero',
            old_name='compañia',
            new_name='compania',
        ),
        migrations.RenameField(
            model_name='compañia',
            old_name='nombre_compañia',
            new_name='nombre_compania',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='compañia',
            new_name='compania',
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sueldo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='valor_por_hora',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='id_prov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_bomberos.proveedor'),
        ),
        migrations.DeleteModel(
            name='DetallePreventivo',
        ),
        migrations.AddField(
            model_name='revisiondiaria',
            name='id_autobombero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bomberos.autobombero'),
        ),
        migrations.AddField(
            model_name='detmant',
            name='id_mantencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_mantencion', to='app_bomberos.mantencion'),
        ),
        migrations.AddField(
            model_name='detmant',
            name='id_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='app_bomberos.servicio'),
        ),
        migrations.AddField(
            model_name='detinsumo',
            name='id_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bomberos.insumo'),
        ),
        migrations.AddField(
            model_name='detinsumo',
            name='id_mantencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_insumo', to='app_bomberos.mantencion'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='tareas_internas',
            field=models.ManyToManyField(blank=True, null=True, to='app_bomberos.tareainterna'),
        ),
    ]
