# Generated by Django 4.2.5 on 2023-12-18 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bomberos', '0002_detinsumo_detmant_insumo_revisiondiaria_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisiondiaria',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
